version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: nest-db-mysql
